### ISSUE TITLE
Wood Crafter & Listtrainers Issues

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#40]
Back again. So every single one of my trainers works except for the Wood Crafter and the /dc listtrainers GUI only displays 11 of my trainers. How do I get them all to show up? What do you think is going on with the Wood Crafter? When you click the "Wood Crafter" nothing happens at all on either click.

**Comment by drekryan** [comment]
Will take a closer look.. thanks

**Comment by drekryan** [comment]
ok so I have found and fixed the wood crafter issue so far. I am still trying to recreate the issue you are having with the list trainers GUI (mine is showing more than 11 so I will have to keep looking to see what may be happening there).

I have opened a pull request for the Wood Crafter issue for Jessy to merge then release on Spigot. The issue is caused by a typo in the skills.csv file which you can fix yourself in the meantime while waiting for the spigot build. Here is how to fix it on your end. Or you can wait for the fix in Spigot build then delete and regen your skills.csv file.

1. stop your server/world
2. Go to DwarfCraft config folder
3. open skills.csv file in a text editor
4. Find the following line "53,Wood Crafter,WOOD,2,1152,280,2,1152,0,0,0,DOOR"
5. edit the word "DOOR" to be "WOOD_DOOR"
6. the line should now look like this "53,Wood Crafter,WOOD,2,1152,280,2,1152,0,0,0,WOOD_DOOR"
7. save skills.csv
8. look at old wood crafter trainer and run command /npc select to select npc
9. run "/npc remove" to delete old invalid trainer
10. recreate the wood crafter trainer

**Comment by tylerking** [comment]
Thanks for the update. I'll keep an eye out for the listtrainers fix.

**Comment by Jessy1237** [comment]
Quick question. After correcting the skill.csv and removing the bugged trainer, does the "/dc listtrainers" work as intended? If not could you possilbly zip and post your DwarfCraft config folder so i can test it out.

**Comment by drekryan** [comment]
@Jessy1237 the trainers arent stored by DC anymore.. they are in citizens save.yml but if you use his save.yml file from citizens the trainers will fail to load because the uuids of the entities wouldnt match without his world as well. hmm :/

**Comment by tylerking** [comment]
Ok the Wood Crafter works as expected now so I tested the listtrainers and noticed that it was only loading the trainers that were close to me. Hope this helps.

**Comment by Jessy1237** [comment]
hmmm odd, i've tp'd myself to 10000,10000 and then restarted my server. After doing this my trainers still show up in the gui. Even went to the nether and did the same thing, and it still worked and teleported me through dimensions. It always seemed to show my 50+ trainers.

**Comment by Jessy1237** [comment]
what plugins are you currently running?

**Comment by tylerking** [comment]
That is odd and it's the same plugins I shared with you last night.

**Comment by Jessy1237** [comment]
Does citizens show it loaded all your npcs in your console on server startup?

**Comment by tylerking** [comment]
Yep. Says I have 85 NPCs loaded.

**Comment by Jessy1237** [comment]
Ok so i've been able to replicate the issue on a new test server. The issue seems to arise when the trainers aren't at spawn so the chunks aren't active, hence the npcs haven't spawned.

**Comment by tylerking** [comment]
Fantastic. I'm glad you found it.

**Comment by Jessy1237** [comment]
The fix is now available on spigot
