### ISSUE TITLE
Keep skill levels on race change

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#44]
Ok...I got one more for you and I swear I'm done asking for stuff...at least for awhile. Could you make it so players could keep their skill levels for each race? This way they don't lose any progress for just swapping to another race?

**Comment by drekryan** [comment]
@doitliketyler hey do you run a public server with DwarfCraft? curious..

**Comment by tylerking** [comment]
I do run a network but the server with Dwarfcraft on it hasn't launched yet.

**Comment by drekryan** [comment]
@doitliketyler oh what is the info if you dont mind? you can private message it to me if you prefer on Twitter (@dreklamb)

**Comment by tylerking** [comment]
Sure. The IP is play.lacunamc.com. We just launched this week.

**Comment by Jessy1237** [comment]
Hmmm i'll have to look into it because the way changing race is treated right now is as if the player is respecing their character. Also some skills would have to be reset as not all races specialise in every skill so they would have to be set to the race level limit if they exceed it once changing race.

**Comment by Jessy1237** [comment]
I could add a config option to make it either be complete reset at race change (hardmode, more of a deterrent in hot swapping races) and the other being as said above resetting to race level limit if they exceed it.

**Comment by tylerking** [comment]
Ok, so the reason I'm asking is that I've created a little roleplay engine in Denizens where a player can have multiple profiles which display their details along with their DwarfCraft race so when the players change their race or swap their profile it also changes their current DwarfCraft race. It all works great except the resetting of the DwarfCraft race skill levels. I would hate for players to lose any progress at all just for swapping their race.

**Comment by Jessy1237** [comment]
You could possibly incorporate your profile system with Denizen with DwarCraft using the DwarfCraft API and create a companion plugin. It might make your profiles work nicer.

**Comment by tylerking** [comment]
Question. So that second option config...if I didn't have any skills the overlapped into other races then no skills would be reset correct?

**Comment by drekryan** [comment]
I don’t know how you have yours setup but here is how it would work in normal DwarfCraft. By default a skill your race specializes in can level to a max of level 30 (this can however be increased in the config) where all other skills are locked at a race level limit which by default is level 5 (can be changed). Let’s say I am the Dwarf race and level Pickaxe Use to level 30 since that is a skill my race specializes in and I level fisherman to level 5. In this example let’s say I decide to change to the Human race. If we added it as a config option this is what would happen. My pickaxe use skill would drop from level 30 to level 5 because Pickaxe Use is a Dwarf skill and I would no longer be a Dwarf. So as a Human, 5 is the max Pickaxe Use could be so I would be reset to that. However my level 5 Fisherman skill is a Human race skill so I would stay at my previous level of 5 in that skill but now since my race specializes in it the level cap would now be 30 so I could level that skill 25 more times than I could before.

Hope that helps clarify.

**Comment by tylerking** [comment]
Oh, thats right. I completely forgot about the 5 and 30 caps. Unfortunately, thats just not going to work for my situation. I would have to remove the multiple profiles unless each race can hold its own stats autonomously because no player is going to want to wipe their progress. Is there no chance for you to make it so each race works as its own profile?

**Comment by drekryan** [comment]
Unfortunately storing multiple profiles in the way I am understanding your request doesn’t align with the way DwarfCraft was built. The underlying code base and database cannot support that and it would be a large amount of work to try to make it work. We have added the ability to put the plugin into soft core mode which would only reset them to the race level limit instead of 0 as mentioned above.

We encourage you however if you are trying to do something custom with DwarfCraft to checkout the API that DwarfCraft provides. There are various events you can run code on, for example level ups and race changes. You can also fully access the config and data manager that powers DwarfCraft as well as soon injecting your own custom commands into the plugin. There is a ton a flexibility with the API. Once you get started with it you will see the variety of things you can access and modify to make DwarfCraft work in a different way than we have provided.

@Jessy1237 can comment further if I have missed something here.

**Comment by tylerking** [comment]
I assumed that was going to be the case but figured Id try and push for it. It doesn't hurt. Thanks for taking the time as always.

I do have a simple request since that's not going to work out. Could you make some placeholderapi placeholders? I'm mainly looking for the race name placeholder.

**Comment by drekryan** [comment]
Sounds like a decent idea.. I’ll put it on the list to look into for the release after next. Next release should be out sometime this week and then we can look into that. I personally would find a lot of use out of placeholders like that so would be happy to add that in.

**Comment by tylerking** [comment]
Awesome. Thanks @drekryan. I'll be looking forward to it.
