### ISSUE TITLE
EntityDamageByEntityEvent Error

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#76]
Getting this in the console from time to time:

https://pastebin.com/raw/CW7iKxqC

**Comment by tylerking** [comment]
Also...the not picking up drops bug is back...it doesn't happen with crafting necessarily...it just happens but not with Dwarfcraft installed.

**Comment by drekryan** [comment]
I’ll take a look tonight/tomorrow into this..

**Comment by drekryan** [comment]
Looks to be a conflict with Sentinel plugin and DwarfCraft.. I’ll see if that’s something we can try to patch on our end, otherwise they may have to fix it. Do you have Sentinel traits on the DwarfCraft trainer NPCs?

**Comment by tylerking** [comment]
Nope

**Comment by drekryan** [comment]
Do you have that plugin installed?

**Comment by tylerking** [comment]
Yes

**Comment by Jessy1237** [comment]
is that the whole error? its just odd that there is a caused by line in the stack trace

**Comment by tylerking** [comment]
It was spamming the console so no it wasn't everything. I'm really just more concerned with this bug with not being able to pick up blocks. It completely destroys the experience on the server and if it's not fixed soon I'm going to have to strip out Dwarfcraft all together which I really don't want to have to do.

**Comment by Jessy1237** [comment]
would you be able to get the full stack trace with the caused by lines from your server log? Otherwise its going to severely delay the debugging process of this issue.

**Comment by tylerking** [comment]
Still waiting on a fix for this.

**Comment by drekryan** [comment]
Like Jessy mentioned above we are requesting a bit more information regarding the issue. Until we know a bit more we don’t really know where to begin looking in the code.

* Is there a full stack trace being printed to the console with a line stating “caused by”
* What steps cause the issue?
* Does it happen every time or just sometimes?
* Is it certain blocks like logs, stone? All blocks?
* Does it happen on blocks harvested from the world or blocks made through crafting?

**Comment by tylerking** [comment]
Well, what you are asking would require me to put it back on a production server with players and to wait for stuff to go wrong which I'm not going to do. It would take me just as long as you to figure out all of that stuff too.

**Comment by drekryan** [comment]
Would you be able to go into the logs folder and fetch me the full log file for March 3 when this crash occurred so i have the full stack trace to go off of?

**Comment by tylerking** [comment]
I would but we remove our logs every 7 days.

**Comment by drekryan** [comment]
Ok I can talk to @Jessy1237 shortly to see if he has any ideas but personally without the crash logs there isn’t much for me to work with. 

I spent an hour on my test server with pure DwarfCraft and am not having any issues not picking up drops.

Currently I believe this issue is caused by the crash with an interaction with Citizens and Sentinels which I was unable to reproduce so I would need the crash log to properly patch it.

When crafting it disables the ability to pickup items before the proper calculations and after those calculations it reenables item pickups. However is a crash occurred in between this it could cause DwarfCraft to halt and be unable to reenable the item pickups. That’s my current theory based off the information given but I really just cannot no for sure because I have no information or crash log from how this happens.

The log you posted basically just tells me that something was null inside the EntityDamageByEntity event and the event couldn’t be handled. But without the full stack trace with the caused by line it doesn’t tell me what was null in that event. So I’m blindly looking for a null value that could possibly be there but I just cannot be sure without the full log.

As of now there is not enough information to fix the issue. As I am unable to reproduce this on a fresh server with DwarfCraft so I’m guessing it’s caused by a plugin interaction which I haven’t been able to recreate.

**Comment by drekryan** [comment]
I think we need to work on an Issue Template for DwarfCraft Issues to prevent issues without enough information. Its best to gather as much information as possible when the issue occurs so we can actually dig through the hundreds of lines of DwarfCraft code to reproduce and debug the issue. 

A generic/vague issue is like a needle in a haystack with the amount of code that DwarfCraft has and there usually isn't much we can do to correct the issue without proper steps to cause the issue, things you tried, things that don't cause the issue, what workarounds do you know for the issue, etc.

That being said this issue currently has insufficient information to investigate this issue and will be marked as "needs more information". If you hit this issue again in the future and would like to update the issue which further information, please reopen this issue at that time.

**Comment by doitliketyler** [comment]
I gave you guys enough information and you have even replicated the issue on your own before. I also told you directly that this happens with the bare minimums installed.
