### ISSUE TITLE
Iron Placing Exploit

### ISSUE THREAD

**Issue by JesterOwl** [Jessy1237/DwarfCraft#79]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Hey, currently is a player maxes out their Dwarf skill trees,
 (ex the Ore Miner Skill that allows for more iron ore drops)
They can place iron ore they've mined, and then break it and it drops two. So if a miner has 4 iron ore and places them and then mines them they'll have 8. 

Is this a bug, if not would it be possible to create a fix for this?

**Comment by drekryan** [comment]
Yes this is possible to fix and will look into that

**Comment by Jessy1237** [comment]
It's not really a bug as thats how the plugin was intended to work but it should be able to create an option that disables this functionality.

**Comment by drekryan** [comment]
@JesterOwl ,

I have implemented a fix for this. @Jessy1237 and I were aware this existed and have been fine with it since, however we do agree for some skills it defeats the purpose of the skill and play of the game.

Some skills in DwarfCraft may allow the duping behavior but for the skills which duping would defeat the purpose of (such as Ore Miner/Exotic Miner) we have decided to prevent the placing exploit. For skills such as Glassworker we have decided to continue to allow this behavior on placed blocks.

After some additional changes and testing a release with this fix will be released on Spigot (expect by the end of the week depending on me and Jessy's free time). Thanks for your interest in DwarfCraft.

**Comment by JesterOwl** [comment]
Thank you! Yea Dwarfcraft has become my favorite plugin over the past few weeks, it provides a super unique feel to our rpg server.

Thank you again for the fast responses and fixes, I really appreciate it.

**Comment by drekryan** [comment]
We love seeing DwarfCraft used in new and unique ways and designed the plugin in a way that we found fun and interesting.

We are always interested in how people are using the plugin as that helps guide us to new ideas for future features and improvements.

A lot of code in DwarfCraft is more than 5 years old and over the latest releases we have been fixing lots of issues with some old skills so if you find a skill that isn’t working as it should please do let us know. We want to bring those all up to date over time.

We aren’t currently working on any new features but are up for ideas. We have been focusing on making the necessary changes for the upcoming 1.13 Minecraft release. There is a lot of work needed here to be 1.13 ready.

Jessy and I have quite a few new ideas we would love to work on.

**Comment by JesterOwl** [comment]
Very excited to see where it goes : )

**Comment by drekryan** [comment]
@JesterOwl 

DwarfCraft 4.1.5 is here! https://www.spigotmc.org/resources/dwarfcraft.4118/update?update=232517

Give it a shot and let me know how it goes in terms of fixing this issue. Let me know if you run into any issues with it (I sometimes derp).

**Keep in mind you do need to regenerate the effects.csv file by deleting the file and letting the plugin recreate it. If you have made custom changes to the file you will need to make the changes to the file manually (see spigot release notes)**

**Comment by JesterOwl** [comment]
@drekryan 

Yup. Working perfectly, thank you for implementing the feature so quickly. Will message if any issues or bugs come up.
